### DISCUSSION TITLE
Easier way to shard documents

### DISCUSSION THREAD

**Discussion by ksylvan** [bmad-code-org/BMAD-METHOD#111] [Ideas]
See issue #110 

Here's the demonstration chat of talking to the agent and having it create a much easier-to-process sharding output:

https://g.co/gemini/share/ab3ff0e8f09d

And then I copy the whole output (using the "..." Copy that preserved the Markdown formatting of the entire output) and run my Python extraction script:

```bash
(fabric-mcp) kayvan@dharma src/fabric-mcp [develop?] $ python scripts/extract_files.py temp_output input.txt
Written: temp_output/docs/epic-1.md
Written: temp_output/docs/epic-2.md
Written: temp_output/docs/epic-3.md
Written: temp_output/docs/epic-4.md
```

And voila! All the epic files are there. Now I look them over, fix the heading levels, and pop them into my `docs/` directory.

```python
#!/usr/bin/env python3
"""
Script to extract files from a specially formatted text file.
The script processes a file that contains embedded file contents, extracts them,
and writes them to specified locations in a destination directory.
"""

import argparse
import os
import re
import sys


def main():
    """Main function to handle argument parsing and file processing."""
    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description="Extract files from a formatted text file."
    )
    parser.add_argument(
        "dest_dir", help="Destination directory where extracted files will be written"
    )
    parser.add_argument(
        "input_file", help="Input file containing file definitions and contents"
    )

    args = parser.parse_args()

    # Make sure destination directory exists
    try:
        os.makedirs(args.dest_dir, exist_ok=True)
    except OSError as e:
        print(
            f"Error creating destination directory '{args.dest_dir}': {e}",
            file=sys.stderr,
        )
        return 1

    # Try to open and process the input file
    try:
        process_input_file(args.input_file, args.dest_dir)
    except (FileNotFoundError, OSError, UnicodeDecodeError) as e:
        print(f"Error processing input file: {e}", file=sys.stderr)
        return 1

    return 0


def process_input_file(input_file: str, dest_dir: str):
    """
    Process the input file and extract embedded files.

    Args:
        input_file (str): Path to the input file
        dest_dir (str): Destination directory for extracted files
    """
    file_pattern = re.compile(r"^\*\*filename: (.*)\*\*$")
    found_first_file = False
    current_filename = ""
    collecting_content = False
    current_content = []

    try:
        with open(input_file, encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n")

                # Check if this line defines a filename
                match = file_pattern.match(line)
                if match:
                    # If we were already collecting content, write the previous file
                    if collecting_content and current_filename:
                        write_file(current_filename, current_content, dest_dir)

                    # Start collecting for a new file
                    found_first_file = True
                    current_filename = match.group(1)
                    collecting_content = False
                    current_content: list[str] = []
                    continue

                # Skip everything until we find the first filename
                if not found_first_file:
                    continue

                # Check for the start/end markers of file content
                if line.startswith("```"):
                    if not collecting_content:
                        # Start collecting content
                        collecting_content = True
                    else:
                        # End of content section, write the file
                        write_file(current_filename, current_content, dest_dir)
                        collecting_content = False
                        current_content = []
                        current_filename = ""
                    continue

                # If we're collecting content, add this line
                if collecting_content:
                    current_content.append(line)

        # Handle case where the file ends while still collecting content
        if collecting_content and current_filename:
            write_file(current_filename, current_content, dest_dir)

    except FileNotFoundError:
        print(f"Input file not found: {input_file}", file=sys.stderr)
        raise
    except OSError as e:
        print(f"Error reading input file: {e}", file=sys.stderr)
        raise


def write_file(filename: str, content: list[str], base_dir: str):
    """
    Write content to a file, creating any necessary directories.

    Args:
        filename (str): Path to the output file, relative to base_dir
        content (list): List of lines to write to the file
        base_dir (str): Base directory for the output file
    """
    # Replace @@@ with ``` in the content
    processed_content = [line.replace("@@@", "```") for line in content]

    # Construct the full path
    full_path = os.path.join(base_dir, filename)

    # Create parent directories if needed
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    # Write the file
    try:
        with open(full_path, "w", encoding="utf-8") as f:
            for line in processed_content:
                f.write(line + "\n")
        print(f"Written: {full_path}")
    except OSError as e:
        print(f"Error writing file {full_path}: {e}", file=sys.stderr)
        raise


if __name__ == "__main__":
    sys.exit(main())
```

The prompt I used is here as a text file:

[sharding-prompt.txt](https://github.com/user-attachments/files/20476164/sharding-prompt.txt)

**Comment by ksylvan** [comment]
The better way to accomplish this is to embed comments in the original documents that include the target filenames, which a post-processing sharding script could then use to perform the sharding.

The entire concept of utilizing the LLM for the sharding of the PRD and architecture document is then rendered obsolete.

**Comment by ksylvan** [comment]
Then it also becomes easy to re-generate everything if you wanted to make an update to a sharded document. What do you think, Brian? @bmadcode

**Reply by bmadcode** [reply]
Yes, this is similar to what I was suggesting with the use of ========= start:filename ========== and ========= end:filename ========== sections within the doc - no worry about markdown confusion - just brute rip out between blocks.

We will need to:

- Update the templates with these marking indications
- Create a new shard script (nodejs and still some tech debt to introduce python scripts - or maybe just keep it simple to node) - or go generic linux style commands, but that always seems to run into issues with windows.
- Potentially need a migration script - there are lots of complaints when I release a change that is somewhat different, so maybe a script that can find all the sections and add the starter and ender tags.

Also - because of the way I set up v3 (in hind site i wish i didnt) - some sections get merged into a single file, instead of smaller granular files. Part of me wants to go back to the smaller granular files though (for example, instead of operational guidelines, have more granular smaller files based on or similar the markdown section names), as I was mistaken in thinking the LLM charges for each individual file it accesses.

What do you think @ksylvan?

**Reply by bmadcode** [reply]
Something like this in the template:

========= start:tech-stack.md ==========

# Technology Stack Selections

{Collaboratively define the core technologies. Be specific about choices and versions where appropriate.}

- **Primary Backend Language/Framework:** {e.g., Python/FastAPI, Node.js/Express, Java/Spring Boot}
- **Primary Frontend Language/Framework (if applicable):** {e.g., TypeScript/React (Next.js), JavaScript/Vue.js}
- **Database:** {e.g., PostgreSQL, MongoDB, AWS DynamoDB}
- **Key Libraries/Services (Backend):** {e.g., Authentication (JWT, OAuth provider), ORM (SQLAlchemy), Caching (Redis)}
- **Key Libraries/Services (Frontend, if applicable):** {e.g., UI Component Library (Material-UI, Tailwind CSS + Headless UI), State Management (Redux, Zustand)}
- **Deployment Platform/Environment:** {e.g., Docker on AWS ECS, Vercel, Netlify, Kubernetes}
- **Version Control System:** {e.g., Git with GitHub/GitLab}

========= end:tech-stack.md ==========

**Comment by ksylvan** [comment]
Yeah, that's fine too, but it doesn't take care of one use case:

The idea of using Markdown comment syntax for the separators is this:

1) The LLM agent does not have to care about it. They do their job of just putting the information in the template and exporting it.

2) Then the generated PRD or architecture document becomes the source of truth for the sharded documents. If you change something that is in a section that is delimited by the markers,

```plaintext
<!-- ===start:tech-stack.md===  -->
# Technology Stack Selections
{Collaboratively define the core technologies. Be specific about choices and versions where appropriate.}

* Primary Backend Language/Framework: {e.g., Python/FastAPI, Node.js/Express, Java/Spring Boot}
* Primary Frontend Language/Framework (if applicable): {e.g., TypeScript/React (Next.js), JavaScript/Vue.js}
* Database: {e.g., PostgreSQL, MongoDB, AWS DynamoDB}
* Key Libraries/Services (Backend): {e.g., Authentication (JWT, OAuth provider), ORM (SQLAlchemy), Caching (Redis)}
* Key Libraries/Services (Frontend, if applicable): {e.g., UI Component Library (Material-UI, Tailwind CSS + Headless UI), State Management (Redux, Zustand)}
* Deployment Platform/Environment: {e.g., Docker on AWS ECS, Vercel, Netlify, Kubernetes}
* Version Control System: {e.g., Git with GitHub/GitLab}
 <!-- ===end:tech-stack.md===  -->
```

Then you can just re-run a command like `node ./shard-document.js PRD.md` to re-generate the documents.

**Comment by bmadcode** [comment]
Ah I think I understand - is it even worth adding the ======= filename separators than, or keep as is, but just update the task rule to wrap the content properly int he markdown comments?

Or maybe a combination of both?

**Comment by ksylvan** [comment]
I am suggesting that we only modify the templates to include the sharding metadata as comments.

This is separate from the system you already use to put multiple documents in one `.txt` file that the `build-web-agent.js` script uses so that you only have to upload a handful of documents to set up your Gem/CustomGPT. We don't have to change that.

Putting these metadata comments in the templates means that your PRD and architecture document already contain within them the instructions for how to shard them.

The only other change would be to remove the "shard document" task from the agents.

**Comment by bmadcode** [comment]
Got it! Ok let do it. Can you pr your script and template changes? If not I
can try to replicate this weekend

**Comment by ksylvan** [comment]
I'll work on this. Might have something by today.

**Comment by ksylvan** [comment]
Hi Brian @bmadcode - Check this new tool out:

I just created it for this purpose: https://github.com/ksylvan/markdown-tree-parser

You can install it via npm:

```bash
$ npm install -g @kayvan/markdown-tree-parser 

added 57 packages in 2s

47 packages are looking for funding
  run `npm fund` for details
```

![image](https://github.com/user-attachments/assets/4cc721f6-b98c-4fb0-bafd-5f5dbb1e60df)

```plaintext
$ md-tree list ~/src/fabric-mcp/docs/architecture.md 

📋 Headings in architecture.md (32 total):

📁 Fabric MCP Server Architecture Document
  📄 Introduction / Preamble
  📄 Technical Summary
  📄 High-Level Overview
  📄 Architectural / Design Patterns Adopted
  📄 Component View
  📄 Project Structure
    📃 Key Directory Descriptions
    📃 Notes
  📄 API Reference
    📃 External APIs Consumed
      📃 Fabric REST API
    📃 Internal APIs Provided (MCP Tools)
  📄 Data Models
    📃 Core Application Entities / Domain Objects
    📃 API Payload Schemas (MCP Tools & Fabric API)
    📃 Database Schemas
  📄 Core Workflow / Sequence Diagrams
    📃 1. MCP Client: Tool Discovery ()
    📃 2. MCP Client: Execute Non-Streaming Pattern (e.g., )
    📃 3. MCP Client: Execute Streaming Pattern ( with )
    📃 4. Server Startup & Fabric API Connectivity Check
  📄 Definitive Tech Stack Selections
  📄 Infrastructure and Deployment Overview
  📄 Error Handling Strategy
  📄 Coding Standards
    📃 Detailed Language & Framework Conventions
      📃 Python Specifics
  📄 Overall Testing Strategy
  📄 Security Best Practices
  📄 Key Reference Documents
  📄 Change Log
```

For example:

```bash
$ md-tree extract ~/src/fabric-mcp/docs/architecture.md 'Coding Standards'

📄 Section "Coding Standards":

## Coding Standards

These standards are mandatory for all code generation by AI agents and human developers. Deviations are not permitted unless explicitly approved and documented as an exception in this section or a linked addendum.

* **Primary Language & Runtime:** Python >=3.11 with CPython (as per Definitive Tech Stack Selections).
* **Style Guide & Linter:**
  * **Tools:** `Ruff` for formatting and primary linting, `Pylint` for additional static analysis, `isort` for import sorting (often managed via Ruff). `Pyright` for static type checking in strict mode.
  * **Configuration:**
    * Ruff: Configured via `.ruff.toml` and/or `pyproject.toml`.
    * Pylint: Configured via `.pylintrc`.
    * isort: Configured in `pyproject.toml` (often via `[tool.ruff.lint.isort]`).
    * Pyright: Configured in `pyproject.toml` (under `[tool.pyright]`) for strict mode.
```

**Comment by ksylvan** [comment]
I'm rethinking my original idea of adding Markdown comment metadata...

I think we might be able to create a sharding config file that basically lists all the headings in the `PRD.md` or `architecture.md` documents that correspond to a sharded document and then a simple script can assemble the sharded documents using my `md-tree` tool.

**Reply by bmadcode** [reply]
This is awesome idea - I checked the repo - great idea. We can add a package.json - will make it easier for various scripts available also. Also going to add an install script (which just copies the bmad-agent folder to a project target).

**Comment by ksylvan** [comment]
Let me think on it a bit more and I'll come up with an excellent PR.

The concept involves a YAML configuration file, likely derived from the current sharding instructions.

Something like this:

### bmad-agent/doc-sharding-config.yaml

```yaml
# Document Sharding Configuration
# Maps destination documents to their source sections for automated sharding

version: "1.0"
description: "Configuration for sharding large project documents into smaller, focused files"

# Configuration for PRD document sharding
prd_sharding:
  source_document: "PRD.md"  # Can be overridden at runtime
  destination_prefix: "docs/"
  sections:
    - destination: "epic-{id}.md"
      source_sections:
        - "Epic {id}:*"  # Matches Epic headings with IDs
        - "**Epic {id}:**"  # Alternative Epic format
      description: "Individual Epic breakdown with user stories"
      pattern_type: "dynamic"  # Uses {id} placeholder
      
# Configuration for Architecture document sharding  
architecture_sharding:
  source_document: "architecture.md"  # Can be overridden at runtime
  destination_prefix: "docs/"
  sections:
    - destination: "api-reference.md"
      source_sections:
        - "API Reference"
        - "API Endpoints"
        - "Service Interfaces"
      description: "API documentation and endpoint specifications"
      
    - destination: "data-models.md"
      source_sections:
        - "Data Models"
        - "Database Schema"
        - "Entity Definitions"
      description: "Data structure and database schema definitions"
      
    - destination: "environment-vars.md"
      source_sections:
        - "Environment Variables Documentation"
        - "Configuration Settings"
        - "Deployment Parameters"
        - "Infrastructure and Deployment Overview" # Extract config details
      description: "Environment variables and configuration settings"
      
    - destination: "project-structure.md"
      source_sections:
        - "Project Structure"
        - "Detailed Frontend Directory Structure"
        - "Backend Repository Structure"
      description: "Code organization and directory structure"
      
    - destination: "tech-stack.md"
      source_sections:
        - "Technology Stack"
        - "Key Technologies"
        - "Libraries and Frameworks"
        - "Definitive Tech Stack Selections"
      description: "Technology choices and framework decisions"
      
    - destination: "operational-guidelines.md"
      source_sections:
        - "Coding Standards"
        - "Development Guidelines"
        - "Best Practices"
        - "Testing Strategy"
        - "Testing Decisions"
        - "QA Processes"
        - "Overall Testing Strategy"
        - "Error Handling Strategy"
        - "Security Best Practices"
      description: "Development practices and operational procedures"
      consolidation_note: "Organize under H3/H4 headings by source section"
      
    - destination: "component-view.md"
      source_sections:
        - "Component View"
        - "Architectural / Design Patterns Adopted"
      description: "System components and architectural patterns"
      
    - destination: "sequence-diagrams.md"
      source_sections:
        - "Core Workflow / Sequence Diagrams"
        - "Workflow Diagrams"
        - "Process Flow"
      description: "System workflows and process diagrams"
      
    - destination: "infra-deployment.md"
      source_sections:
        - "Infrastructure and Deployment Overview"
        - "Deployment Strategy"
        - "Cloud Infrastructure"
      description: "Infrastructure setup and deployment processes"
      
    - destination: "key-references.md"
      source_sections:
        - "Key Reference Documents"
        - "Related Documentation"
        - "External References"
      description: "Links to related documentation and external resources"

# Configuration for Frontend-specific document sharding
frontend_sharding:
  source_document: "front-end-architecture.md"  # Can be overridden at runtime
  destination_prefix: "docs/"
  sections:
    - destination: "front-end-project-structure.md"
      source_sections:
        - "Front-End Project Structure"
        - "Detailed Frontend Directory Structure"
        - "Component Organization"
      description: "Frontend code organization and file structure"
      
    - destination: "front-end-style-guide.md"
      source_sections:
        - "UI Style Guide"
        - "Brand Guidelines"
        - "Visual Design Specifications"
        - "Styling Approach"
      description: "UI styling guidelines and design system"
      
    - destination: "front-end-component-guide.md"
      source_sections:
        - "Component Library"
        - "Reusable UI Components Guide"
        - "Atomic Design Elements"
        - "Component Breakdown & Implementation Details"
      description: "Component library and reusable UI elements"
      
    - destination: "front-end-coding-standards.md"
      source_sections:
        - "Front-End Coding Standards"
        - "JavaScript/TypeScript Style"
        - "CSS Naming Conventions"
        - "Accessibility Best Practices"
      description: "Frontend-specific coding conventions and standards"
      
    - destination: "front-end-state-management.md"
      source_sections:
        - "State Management In-Depth"
        - "State Architecture"
        - "Data Flow Patterns"
      description: "State management patterns and data flow"
      
    - destination: "front-end-api-interaction.md"
      source_sections:
        - "API Interaction Layer"
        - "HTTP Client Setup"
        - "Data Fetching Patterns"
      description: "Frontend API communication and data fetching"
      
    - destination: "front-end-routing-strategy.md"
      source_sections:
        - "Routing Strategy"
        - "Navigation Patterns"
        - "Route Configuration"
      description: "Frontend routing and navigation implementation"
      
    - destination: "front-end-testing-strategy.md"
      source_sections:
        - "Frontend Testing Strategy"
        - "Component Testing"
        - "UI Testing Patterns"
      description: "Frontend testing approaches and methodologies"

# Global settings
global_settings:
  # Whether to update docs/index.md after sharding
  update_index: true
  
  # Index file configuration
  index_file: "docs/index.md"
  
  # Whether to preserve source document after sharding
  preserve_source: true
  
  # Default extraction behavior
  extraction_mode: "verbatim"  # Don't modify content during extraction
  
  # Whether to create destination directories if they don't exist
  create_directories: true
  
  # Backup settings
  create_backup: true
  backup_suffix: ".backup"
  
  # Content formatting
  preserve_markdown_formatting: true
  include_section_headers: true
  
  # Error handling
  skip_missing_sections: true
  warn_on_missing_sections: true

# Metadata for tracking
metadata:
  created_by: "bmad-agent"
  version: "1.0"
  last_updated: "2025-05-30"
  description: "Configuration for automated document sharding to improve developer documentation accessibility"

```
