### ISSUE TITLE
/po create-doc in IDE adds advanced elicitation questions into .md files

### ISSUE THREAD

**Issue by clarsen** [bmad-code-org/BMAD-METHOD#278]
**Describe the bug**

When asked to create the missing or enhance an existing document in the IDE, the product owner, in addition to creating content, adds the advanced elicitation questions to the Markdown text.

**Steps to Reproduce**
1. with existing project and existing `docs/architecture/front-end-architecture.md`, run `/po create-doc docs/architecture/front-end-architecture.md`
2. select option to enhance existing document according to template (I forget the exact wording)

or
1. with existing project and missing `docs/architecture/components.md`, but existing `docs/architecture/components-view.md`, run `/po create-doc docs/architecture/components.md`
2. select option to enhance existing document according to template (I forget the exact wording)

the actual paths I use are different due to monorepo layout (see `core-config.yml` below)

**PR**
none available yet

**Expected behavior**

These repeated text at end of each section shouldn't be present:

```
**Advanced Reflective, Elicitation & Brainstorming Actions**
Choose an action (0-9 - 9 to bypass - HELP for explanation of these options):

0. Expand or Contract for Audience
1. Explain Reasoning (CoT Step-by-Step)
2. Critique and Refine
3. Analyze Logical Flow and Dependencies
4. Assess Alignment with Overall Goals
5. Identify Potential Risks and Unforeseen Issues
6. Challenge from Critical Perspective (Self or Other Persona)
7. Explore Diverse Alternatives (ToT-Inspired)
8. Hindsight is 20/20: The 'If Only...' Reflection
9. Proceed / No Further Actions
```

**Please be Specific if relevant**
Model(s) Used: Sonnet-4

Agentic IDE Used: Cursor, but using Claude Code in terminal.
WebSite Used:
Project Language: node.js, python
BMad Method version: 4.20.1

**Screenshots or Links**

**Additional context**

repo is a monorepo with docs organized into a subdirectory under docs/xxxx, but `.bmad-core/core-config.yml` is set properly, i.e.
```yaml
version: 4.20.1
markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/genai-testlab/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/genai-testlab/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/genai-testlab/architecture/coding-standards.md
  - docs/genai-testlab/architecture/tech-stack.md
  - docs/genai-testlab/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/genai-testlab/stories
```

The reason I thought to create these files in the first place is that the Scrum Master looked for those files when creating the next UI story.
